// src/pages/Risk/TransactionActivityRules.jsx

import React, { useState, useEffect } from "react";
import { transactionActivityRuleService } from "../../services/transactionActivityRuleService";
import { toast } from "react-toastify";
import {
  PlusIcon,
  PencilIcon,
  TrashIcon,
  MagnifyingGlassIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import {
  transactionTypeOptions,
  parameterOptions,
  countMatchTypeOptions,
  thresholdMatchTypeOptions,
  frequencyOptions,
  statusOptions,
} from "../../data/transactionActivityRuleOptions";

const TransactionActivityRules = () => {
  // State management
  const [rules, setRules] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [searchTerm, setSearchTerm] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [editingRule, setEditingRule] = useState(null);
  const [saving, setSaving] = useState(false);

  // Form state
  const [formData, setFormData] = useState({
    rule_number: "",
    transaction_type: "",
    parameter: "",
    count_match_type: "",
    transaction_count: "",
    threshold_match_type: "",
    threshold: "",
    frequency: "",
    is_active: "true", // Use string for dropdown compatibility
    activity_rule_score: "",
    rule_display_name: "",
    rule_description: "",
  });

  // Fetch rules on mount
  useEffect(() => {
    fetchRules();
  }, []);

  // Fetch rules from database
  const fetchRules = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await transactionActivityRuleService.getTransactionActivityRules();
      if (result.success) {
        setRules(result.data || []);
      } else {
        setError(result.error || "Failed to load rules");
        toast.error("Failed to load transaction activity rules");
      }
    } catch (err) {
      console.error("Error fetching rules:", err);
      setError("Failed to load transaction activity rules");
      toast.error("Failed to load transaction activity rules");
    } finally {
      setLoading(false);
    }
  };

  // Load next rule number for new rule
  useEffect(() => {
    if (showForm && !editingRule) {
      loadNextRuleNumber();
    }
  }, [showForm, editingRule]);

  const loadNextRuleNumber = async () => {
    const result = await transactionActivityRuleService.getNextRuleNumber();
    if (result.success) {
      setFormData((prev) => ({ ...prev, rule_number: result.ruleNumber }));
    }
  };

  // Handle form input changes
  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value,
    }));
  };

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    setSaving(true);

    try {
      // Prepare form data with proper type conversions
      const payload = {
        transaction_type: formData.transaction_type || null,
        parameter: formData.parameter || null,
        count_match_type: formData.count_match_type || null,
        transaction_count: formData.transaction_count || null, // Keep as text
        threshold_match_type: formData.threshold_match_type || null,
        threshold: formData.threshold || null, // Keep as text
        frequency: formData.frequency || null,
        is_active: formData.is_active === true || formData.is_active === "true",
        activity_rule_score: parseInt(formData.activity_rule_score) || 0,
        rule_display_name: formData.rule_display_name || "",
        rule_description: formData.rule_description || null,
      };

      let result;
      if (editingRule) {
        // Update existing rule - include rule_number for update
        result = await transactionActivityRuleService.updateTransactionActivityRule(
          editingRule.id,
          {
            ...payload,
            rule_number: parseInt(formData.rule_number) || 0,
          }
        );
      } else {
        // Create new rule - rule_number will be auto-generated by service
        result = await transactionActivityRuleService.createTransactionActivityRule(payload);
      }

      if (result.success) {
        toast.success(
          editingRule
            ? "Rule updated successfully"
            : "Rule created successfully"
        );
        setShowForm(false);
        setEditingRule(null);
        resetForm();
        fetchRules();
      } else {
        toast.error(result.error || "Failed to save rule");
      }
    } catch (err) {
      console.error("Error saving rule:", err);
      toast.error("Failed to save rule");
    } finally {
      setSaving(false);
    }
  };

  // Reset form
  const resetForm = () => {
    setFormData({
      rule_number: "",
      transaction_type: "",
      parameter: "",
      count_match_type: "",
      transaction_count: "",
      threshold_match_type: "",
      threshold: "",
      frequency: "",
      is_active: "true", // Use string for dropdown compatibility
      activity_rule_score: "",
      rule_display_name: "",
      rule_description: "",
    });
  };

  // Handle edit
  const handleEdit = (rule) => {
    setEditingRule(rule);
    setFormData({
      rule_number: rule.rule_number || "",
      transaction_type: rule.transaction_type || "",
      parameter: rule.parameter || "",
      count_match_type: rule.count_match_type || "",
      transaction_count: rule.transaction_count || "",
      threshold_match_type: rule.threshold_match_type || "",
      threshold: rule.threshold || "",
      frequency: rule.frequency || "",
      is_active: rule.is_active !== undefined ? (rule.is_active ? "true" : "false") : "true",
      activity_rule_score: rule.activity_rule_score || "",
      rule_display_name: rule.rule_display_name || "",
      rule_description: rule.rule_description || "",
    });
    setShowForm(true);
  };

  // Handle delete
  const handleDelete = async (id) => {
    if (!window.confirm("Are you sure you want to delete this rule?")) {
      return;
    }

    try {
      const result = await transactionActivityRuleService.deleteTransactionActivityRule(id);
      if (result.success) {
        toast.success("Rule deleted successfully");
        fetchRules();
      } else {
        toast.error(result.error || "Failed to delete rule");
      }
    } catch (err) {
      console.error("Error deleting rule:", err);
      toast.error("Failed to delete rule");
    }
  };

  // Handle toggle status
  const handleToggleStatus = async (id, currentStatus) => {
    try {
      const result = await transactionActivityRuleService.toggleRuleStatus(
        id,
        !currentStatus
      );
      if (result.success) {
        toast.success(
          `Rule ${!currentStatus ? "activated" : "deactivated"} successfully`
        );
        fetchRules();
      } else {
        toast.error(result.error || "Failed to update rule status");
      }
    } catch (err) {
      console.error("Error toggling rule status:", err);
      toast.error("Failed to update rule status");
    }
  };

  // Filter rules by search term
  const filteredRules = rules.filter(
    (rule) =>
      rule.rule_display_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      rule.rule_description?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      rule.rule_number?.toString().includes(searchTerm) ||
      rule.parameter?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      {/* Header */}
      <div className="mb-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">
              Transaction Activity Rules
            </h1>
            <p className="text-gray-600 mt-2">
              Rules that can be triggered when a transaction is created
            </p>
          </div>
          <button
            onClick={() => {
              setEditingRule(null);
              resetForm();
              setShowForm(true);
            }}
            className="flex items-center gap-2 px-5 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors shadow-sm hover:shadow-md font-medium"
          >
            <PlusIcon className="w-5 h-5" />
            Add New Rule
          </button>
        </div>
      </div>

      {/* Search */}
      {!showForm && (
        <div className="mb-6">
          <div className="relative max-w-md">
            <MagnifyingGlassIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              type="text"
              placeholder="Search rules..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
          </div>
        </div>
      )}

      {/* Form Modal */}
      {showForm && (
        <div className="fixed inset-0 z-50 overflow-y-auto">
          <div className="flex items-center justify-center min-h-screen px-4 pt-4 pb-20 text-center sm:block sm:p-0">
            <div
              className="fixed inset-0 transition-opacity bg-gray-500 bg-opacity-75"
              onClick={() => {
                setShowForm(false);
                setEditingRule(null);
                resetForm();
              }}
            ></div>

            <div className="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-4xl sm:w-full">
              <div className="bg-white px-4 pt-5 pb-4 sm:p-6 max-h-[90vh] overflow-y-auto">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="text-lg font-medium text-gray-900">
                    {editingRule ? "Edit Rule" : "Create New Rule"}
                  </h3>
                  <button
                    onClick={() => {
                      setShowForm(false);
                      setEditingRule(null);
                      resetForm();
                    }}
                    className="text-gray-400 hover:text-gray-600"
                  >
                    <XMarkIcon className="w-6 h-6" />
                  </button>
                </div>

                <form onSubmit={handleSubmit} className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {/* Rule Number - Auto-generated, read-only */}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Rule Number <span className="text-red-500">*</span>
                      </label>
                      <input
                        type="number"
                        name="rule_number"
                        value={formData.rule_number}
                        readOnly
                        className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50 text-gray-600"
                      />
                    </div>

                    {/* Transaction Type */}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Transaction Type <span className="text-red-500">*</span>
                      </label>
                      <select
                        name="transaction_type"
                        value={formData.transaction_type}
                        onChange={handleInputChange}
                        required
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      >
                        <option value="">Select Transaction Type</option>
                        {transactionTypeOptions.map((option) => (
                          <option key={option.value} value={option.value}>
                            {option.label}
                          </option>
                        ))}
                      </select>
                    </div>

                    {/* Parameter */}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Parameter <span className="text-red-500">*</span>
                      </label>
                      <select
                        name="parameter"
                        value={formData.parameter}
                        onChange={handleInputChange}
                        required
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      >
                        <option value="">Select Parameter</option>
                        {parameterOptions.map((option) => (
                          <option key={option.value} value={option.value}>
                            {option.label}
                          </option>
                        ))}
                      </select>
                    </div>

                    {/* Count Match Type */}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Count Match Type <span className="text-red-500">*</span>
                      </label>
                      <select
                        name="count_match_type"
                        value={formData.count_match_type}
                        onChange={handleInputChange}
                        required
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      >
                        <option value="">Select Count Match Type</option>
                        {countMatchTypeOptions.map((option) => (
                          <option key={option.value} value={option.value}>
                            {option.label}
                          </option>
                        ))}
                      </select>
                    </div>

                    {/* Transaction Count */}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Transaction Count
                      </label>
                      <input
                        type="text"
                        name="transaction_count"
                        value={formData.transaction_count}
                        onChange={handleInputChange}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      />
                    </div>

                    {/* Threshold Match Type */}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Threshold Match Type <span className="text-red-500">*</span>
                      </label>
                      <select
                        name="threshold_match_type"
                        value={formData.threshold_match_type}
                        onChange={handleInputChange}
                        required
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      >
                        <option value="">Select Threshold Match Type</option>
                        {thresholdMatchTypeOptions.map((option) => (
                          <option key={option.value} value={option.value}>
                            {option.label}
                          </option>
                        ))}
                      </select>
                    </div>

                    {/* Threshold */}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Threshold
                      </label>
                      <input
                        type="text"
                        name="threshold"
                        value={formData.threshold}
                        onChange={handleInputChange}
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      />
                    </div>

                    {/* Frequency */}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Frequency <span className="text-red-500">*</span>
                      </label>
                      <select
                        name="frequency"
                        value={formData.frequency}
                        onChange={handleInputChange}
                        required
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      >
                        <option value="">Select Frequency</option>
                        {frequencyOptions.map((option) => (
                          <option key={option.value} value={option.value}>
                            {option.label}
                          </option>
                        ))}
                      </select>
                    </div>

                    {/* Active/Inactive */}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Status <span className="text-red-500">*</span>
                      </label>
                      <select
                        name="is_active"
                        value={formData.is_active}
                        onChange={(e) => {
                          setFormData((prev) => ({
                            ...prev,
                            is_active: e.target.value === "true",
                          }));
                        }}
                        required
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      >
                        {statusOptions.map((option) => (
                          <option key={option.value} value={option.value}>
                            {option.label}
                          </option>
                        ))}
                      </select>
                    </div>

                    {/* Activity Rule Score */}
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-1">
                        Activity Rule Score <span className="text-red-500">*</span>
                      </label>
                      <input
                        type="number"
                        name="activity_rule_score"
                        value={formData.activity_rule_score}
                        onChange={handleInputChange}
                        required
                        min="0"
                        className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      />
                    </div>
                  </div>

                  {/* Rule Display Name - Full width */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Rule Display Name <span className="text-red-500">*</span>
                    </label>
                    <input
                      type="text"
                      name="rule_display_name"
                      value={formData.rule_display_name}
                      onChange={handleInputChange}
                      required
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>

                  {/* Rule Description - Full width */}
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">
                      Rule Description
                    </label>
                    <textarea
                      name="rule_description"
                      value={formData.rule_description}
                      onChange={handleInputChange}
                      rows={3}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>

                  {/* Form Actions */}
                  <div className="flex justify-end gap-3 pt-4">
                    <button
                      type="button"
                      onClick={() => {
                        setShowForm(false);
                        setEditingRule(null);
                        resetForm();
                      }}
                      className="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 transition-colors"
                    >
                      Cancel
                    </button>
                    <button
                      type="submit"
                      disabled={saving}
                      className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {saving ? "Saving..." : editingRule ? "Update Rule" : "Create Rule"}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Rules List */}
      {!showForm && (
        <div className="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
          {loading ? (
            <div className="p-12 text-center">
              <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
              <p className="mt-2 text-gray-600">Loading rules...</p>
            </div>
          ) : error ? (
            <div className="p-12 text-center">
              <p className="text-red-600">{error}</p>
            </div>
          ) : filteredRules.length === 0 ? (
            <div className="p-12 text-center">
              <p className="text-gray-500">No rules found</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Rule #
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Display Name
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Parameter
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Frequency
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Status
                    </th>
                    <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {filteredRules.map((rule) => (
                    <tr key={rule.id} className="hover:bg-blue-50 transition-colors">
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-semibold text-gray-900">
                        {rule.rule_number}
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-900 font-medium">
                        {rule.rule_display_name}
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-600">
                        {rule.parameter || "N/A"}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                        {rule.frequency || "N/A"}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span
                          className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium cursor-pointer transition-colors ${
                            rule.is_active
                              ? "bg-green-100 text-green-800 hover:bg-green-200"
                              : "bg-gray-100 text-gray-800 hover:bg-gray-200"
                          }`}
                          onClick={() => handleToggleStatus(rule.id, rule.is_active)}
                        >
                          {rule.is_active ? "Active" : "Inactive"}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <div className="flex justify-end gap-3">
                          <button
                            onClick={() => handleEdit(rule)}
                            className="text-blue-600 hover:text-blue-800 transition-colors"
                            title="Edit rule"
                          >
                            <PencilIcon className="w-5 h-5" />
                          </button>
                          <button
                            onClick={() => handleDelete(rule.id)}
                            className="text-red-600 hover:text-red-800 transition-colors"
                            title="Delete rule"
                          >
                            <TrashIcon className="w-5 h-5" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default TransactionActivityRules;
